swagger: '2.0'
title: Recipes API
version: '1.0.0'
description: 'This is a sample recipes API. You can find out more about the API at https://github.com/PacktPublishing/Building-Distributed-Applications-in-Gin'
contact:
  name: Tony Lopez
  url: tonylopez.net
  email: tony@lopez.io
schemes: [http]
host: localhost:8080
basePath: /
consumes: [application/json]
produces: [application/json]
paths:
  /recipes:
    get:
      produces: [application/json]
      summary: 'List all recipes'
      description: 'It returns a list of nested objects which contains all recipes'
      responses:
        200:
          description: Succesful Operation
        400:
          description: Bad Request
        404:
          description: Categories Not Found
        500:
          description: Server Error
  /recipes/{id}:
    get:
      produces: [application/json]
      summary: 'Update recipe'
      description: 'It updates the recipe specified by the id parameter'
      parameters:
        - name: id
          in: path
          description: ID of the recipe
          required: true
          type: string
      responses:
        200:
          description: Succesful Operation
        400:
          description: Invalid Input
        404:
          description: Invalid Recipe
        500:
          description: Server Error
